version: '3'
services:
    web:
        #build new image from source
        #build: .
        #use pre-build image
        image: "pianomanfrazier/lemmings"
        ports:  
            - "3000:3000"
        depends_on:
            - mongo
    mongo:
        image: "mongo"
