version: '3'
services:
    web:
        build: .
        #image: "pianomanfrazier/lemmings"
        ports:  
            - "3000:3000"
        depends_on:
            - mongo
    mongo:
        image: "mongo"
